### PR TITLE
Background colour not being applied to ios image from svg

### LINKED ISSUE #241: Background colour not being applied to iOS image from SVG
# Description

Background colour not being applied to iOS image from SVG.

## Reproduction Steps

Using the `iOS` section the background should be `#ffffff`.

```json
{
  "$schema": "https://mobilebuildtools.com/schemas/v2/resourceDefinition.schema.json",
  "android": {
      "resourceType": "Mipmap",
      "name": "icon",
      "scale": 0.1875,
      "additionalOutputs": [
          {
              "name": "launcher_foreground",
              "resourceType": "Mipmap",
              "scale": 0.28125,
              "padFactor": 1.5
          },
          {
              "name": "logo",
              "resourceType": "Drawable"
          }
      ]
  },
  "iOS": {
      "name": "AppIcon",
      "background": "#ffffff",
      "additionalOutputs": [
          {
              "name": "logo"
          }
      ]
  }
}
```

## Expected Behavior

The icon background is white.

## Actual Behavior

Screenshot 2021-06-15 at 23 44 03

## Reproduction App

[template.zip](https://github.com/dansiegel/Mobile.BuildTools/files/6659136/template.zip)

### PR DESCRIPTION
**Pull request by bijington**
The issue solved is:

- [x] Default background is not applied on iOS app icons

Fixes #241

### CODE REVIEW

File: src/Mobile.BuildTools/Generators/Images/ImageResizeGenerator.cs [hunk 1]
```diff
@@ -1,167 +1,163 @@
...
-
-                using var stream = File.Create(outputImage.OutputFile);
-                outputBitmap.Encode(stream, SKEncodedImageFormat.Png, 100);
-            }
-            catch (System.Exception ex)
-            {
-#if DEBUG
-                if (System.Diagnostics.Debugger.IsAttached)
-                    System.Diagnostics.Debugger.Break();
-                else if(!RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
```
Comment (bijington) [inline src/Mobile.BuildTools/Generators/Images/ImageResizeGenerator.cs:79]: Looks like this merge didn't go smoothly

**Review by dansiegel — APPROVED** [review]
